name: Formatting and linting

on: [push]

jobs:
  check-formatting-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
      - name: Install black and flake8
        run: python -m pip install black flake8
      - name: Debug line endings for flagged files
        run: |
          echo "==> File info:"
          file bloqcat/db/__init__.py
          file docs/conf.py
          echo "==> First few lines with control characters:"
          cat -A bloqcat/db/__init__.py | head -n 5
          cat -A docs/conf.py | head -n 5
      - name: Run flake8
        run: flake8
      - name: Run black
        run: black --check --verbose --extend-exclude=".resources." .