name: Formatting and linting

on: [push]

jobs:
  check-formatting-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies via Poetry
        run: poetry install
        
      - name: Normalize line endings to LF
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix bloqcat/db/__init__.py docs/conf.py

      - name: Run flake8
        run: poetry run flake8

      - name: Run black
        run: poetry run black --check --verbose --extend-exclude=".resources." .